routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('index');

Route::get('/privacy-policy', 'HomeController@policyFile')->name('policy');
Route::get('/processing-personal-data', 'HomeController@processingPersonalDataFile')->name('processing-personal-data');
Route::get('/user-agreement', 'HomeController@userAgreementFile')->name('user-agreement');

Route::get('/faq', 'HomeController@faq')->name('faq');

Route::prefix('search')->name('search.')->group(function () {
    Route::get('', 'SearchController@index')->name('index');
});

Route::group(['prefix' => 'service', 'as' => 'service.'], function () {
    Route::get('', 'ServiceController@index')->name('index');
    Route::get('{service}', 'ServiceController@show')->name('detail');
    Route::get('{service}/detail-admin', 'ServiceController@adminDetail')->name('detail-admin')->middleware(['admin.user']);
    Route::get('{service}/form/{ticket?}', 'ServiceController@showForm')->name('form');
    Route::post('{service}/form/{ticket?}', 'ServiceController@storeForm')->name('store-form');
    Route::get('{service}/form-order', 'ServiceController@storeTicketFromOrder')->name('form-order');
    Route::post('{service}/draft/{ticket?}', 'ServiceController@storeDraft')->name('store-draft');
});

Route::prefix('discussions')->name('discussions.')->middleware('invited.forbid')->group(function () {
    Route::get('', 'DiscussionController@index')->name('index');
    Route::get('new', 'DiscussionController@create')->name('create');
    Route::get('{discussion}', 'DiscussionController@show')->name('show');
    Route::post('', 'DiscussionController@store')->name('store');
});

Route::group(['middleware' => ['auth', 'confirm.email', 'twofactor']], function () {
    Route::get('home', 'HomeController@home')->name('home');
    Route::get('profile', 'HomeController@profile')->name('profile.index');
    Route::post('profile', 'HomeController@updateProfile')->name('profile.update');
    Route::get('mesages', 'HomeController@mesages')->name('mesages.index');
    Route::get('notices', 'HomeController@notices')->name('notices.index');
    Route::get('invites', 'HomeController@invites')->name('invites.index');

    Route::get('report', 'TicketController@report')->name('report');
    Route::get('report/export', 'TicketController@ticketsExport')->name('report-export');

    //Route::prefix('search')->name('search.')->group(function () {
    //    Route::get('', 'SearchController@index')->name('index');
    //});

    Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {
        Route::get('', 'TicketController@index')->name('index');
        Route::get('/archive', 'TicketController@archive')->name('archive');
        Route::post('', 'TicketController@window')->name('window');
        Route::get('{ticket}', 'TicketController@show')->name('show');
        Route::post('{ticket}/comment', 'CommentController@store')->name('comment.new');
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('', 'OrderController@index')->name('index');
        Route::get('/create', 'OrderController@create')->name('create');
        Route::post('/update/{order}', 'OrderController@update')->name('update');
        Route::post('/store', 'OrderController@store')->name('store');
        Route::post('/store-draft', 'OrderController@storeDraft')->name('store_draft');
        Route::post('/update/{order}', 'OrderController@update')->name('update');
        Route::post('/update-draft/{order}', 'OrderController@updateDraft')->name('update_draft');
        Route::get('/{order}', 'OrderController@show')->name('show');
    });

    Route::group(['prefix' => 'api', 'namespace' => 'Api'], function () {
        Route::get('ticket', 'TicketController@index');
        Route::get('ticket/archive', 'TicketController@archive')->name('api.ticket.archive');
        Route::get('ticket/{ticket}', 'TicketController@show');
        Route::post('ticket/{ticket}/comment', 'TicketController@comment');
        Route::post('ticket/{ticket}/status', 'TicketController@changeStatus')->name('api.ticket.status');
        Route::post('tickets/comment', 'TicketController@createComments');
        Route::post('tickets/status', 'TicketController@changeStatuses');

        Route::get('order', 'OrderController@index');
        Route::post('order/filtered-users', 'OrderController@filteredUsers');
        Route::post('order/select-user', 'OrderController@selectUser');
        Route::post('order/select-category', 'OrderController@selectCategory');
        Route::post('order/select-service', 'OrderController@selectService');
        Route::get('order/{order}', 'OrderController@show');
        Route::post('order/{order}/status', 'OrderController@changeStatus')->name('api.order.status');
        Route::post('order/{order}/update-service', 'OrderController@updateService');

        Route::post('ticket/{ticket}/updateCheckList', 'TicketController@updateCheckList')->name('api.ticket.updateCheckList');

        Route::get('user', 'UserController@index');

        Route::delete('notification/{notification}', 'NotificationController@destroy')->name('api.notification.delete');
        Route::delete('invite/{invite}', 'InviteController@delete')->name('api.invite.delete');

        Route::get('invite', 'InviteController@index')->name('api.invite.index');
        Route::get('invite/available', 'InviteController@available')->name('api.invite.available');

        Route::post('affiliate/select-operators', 'AffiliateController@selectOperators');
        Route::post('affiliate/select-windows', 'AffiliateController@selectWindows');

        Route::prefix('discussions')->group(function () {
            Route::get('{discussion}/change-is-alert', 'DiscussionController@changeIsAlert')->name('changeisalert');

            Route::prefix('messages')->group(function () {
                Route::post('{discussion}', 'DiscussionController@sendMessage')->name('send');
                Route::get('{message}/read', 'DiscussionController@read')->name('read');
            });
        });

        Route::get('service-categories', 'ServiceController@getServiceCategories')->name('api.service-category');
    });
});

Route::group(['prefix' => 'admin', 'middleware' => 'confirm.email', 'twofactor'], function () {
    Voyager::routes();
    Route::put('settings', 'Voyager\SettingsController@update')->name('voyager.settings.update');
    Route::put('settings/{id}/delete_value', 'Voyager\SettingsController@delete_value')->name('voyager.settings.delete_value');

    Route::group(['middleware' => 'admin.user'], function () {
        Route::post('tickets/{ticket}/comment', 'CommentController@operatorStore')->name('operator.add.ticket');
        Route::post('tickets/{ticket}/comment/set-all-readed', 'CommentController@setAllReaded')->name('operator.read.tickets');

        Route::post('services/{service}/document', 'Api\\DocumentController@store');
        Route::put('services/{service}/document/{serviceDocument}', 'Api\\DocumentController@update');
        Route::delete('services/{service}/document/{serviceDocument}', 'Api\\DocumentController@delete');
        Route::get('services/{service}/copy', 'Voyager\\ServiceController@copy')->name('operator.copy.service');
        Route::get('supports/{support}/copy', 'Voyager\\SupportController@copy')->name('operator.copy.support');

        Route::post('services/affiliate-services', 'Api\\ServiceController@store');
    });
});

Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
    Route::get('', 'CategoryController@category')->name('index');
    Route::get('{serviceCategory}', 'CategoryController@show')->name('detail');
});

Route::get('verify-authentication/resend', 'Auth\TwoFactorController@resend')
    ->middleware('twofactor')
    ->name('verify-authentication.resend');
Route::resource('verify-authentication', 'Auth\TwoFactorController')
    ->middleware('twofactor')
    ->only(['index', 'store']);

Route::get('login/registered', 'HomeController@confirm')->middleware('auth')->name('confirm');
Route::get('login/confirm', 'HomeController@confirmation')->middleware('auth')->name('confirmation');
Route::get('auth/confirm/{user}', 'Voyager\UserController@confirmation')->name('confirmation.auth');

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use App\Services\SearchService;
use Illuminate\Http\Request;

class SearchController extends Controller
{
    /**
     * @var \App\Services\SearchService
     */
    private SearchService $service;

    public function __construct(SearchService $service)
    {
        $this->service = $service;
    }

    public function index(Request $request)
    {
        $search = $request->get('search', '');

        $services = $this->service->searchByService($search) ?? collect();

        return view('search.index', compact('search', 'services'));
    }
}

resources/views/search/index.blade.php
@extends('layouts.site')

@section('content')
    <div class="container">
        <h1 class="mb-4">Результаты поиска</h1>
        <div class="row">
            <div class="col-xl-12 col-12">
                <div class="row">        
                    @foreach ($services as $service) 
                        <!-- <div class="content shadow-sm p-5">
                            <div class="row"> -->
                                <!-- <div class="card card-custom gutter-b col-4">
                                    <div class="card-header">
                                        <div class="card-title">
                                            <span class="card-icon">
                                                <i class="la la-filter text-primary"></i>
                                            </span>
                                            <h3 class="card-label">Область поиска</h3>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <form action="{{ route('search.index') }}" method="get">
                                            <div class="form-group">
                                                <label class="form-label" for="search">Поиск</label>
                                                <input name="search" class="form-control" id="search" type="text" value="{{ old('search') ?? $search ?? '' }}">
                                            </div>
                                            <button type="submit" class="btn btn-primary">Найти</button>
                                        </form>
                                    </div>
                                </div> -->
                                <div class="col-md-4 mb-4">
                                    <div class="category card border-0 shadow-sm p-4">
                                        <div class="card-title mb-3">
                                            <h5 class="fw-bold">
                                                <a href="{{ route('service.detail', $service) }}" class="category-link fw-bold">
                                                    {{ $service->name }}
                                                </a>
                                            </h5>
                                        </div> 
                                        <div class="card-body text-muted">
                                            {!! $service->predescription !!}
                                        </div>   
                                        <div class="card-footer d-flex align-items-center justify-content-between border-0 bg-transparent px-0 pt-4">
                                            <div class="text-start">
                                                @if($service->use_button === 'Y')
                                                    <small class="rounded-pill bg-warning text-sm text-dark py-1 px-3">Сопроводительная</small>    
                                                @elseif ($service->use_button === 'N')
                                                    <small class="rounded-pill bg-light text-sm text-dark py-1 px-3">Информационная</small>    
                                                @endif
                                            </div>
                                            <div class="text-end">
                                                <a href="{{ route('service.detail', $service) }}" class="stretched-link"> <i class="fa fa-chevron-circle-right fa-2x"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div> 
                                

                                <!-- <h3 class=""><a href="{{ route('service.detail', $service) }}">{{ $service->name}}</a></h3>
                                <div class="card-body">
                                    <div class="w-100"> {!! $service->predescription !!}</div>
                                    <div class="d-flex justify-content-end">
                                        <a href="{{ route('service.detail', $service) }}"
                                        class="btn btn-outline-blue rounded-pill px-4 mt-3">
                                            Подробнее
                                        </a>
                                    </div>
                                </div> -->
                            <!-- </div>
                                    

                            </div>
                        </div> -->
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/search/searchform.blade.php
<div class="container mt-4">
    <div class="search_form" id="">
        <form id="search_form" action="{{ route('search.index') }}" method="get">
            <div class="input-group">
                <input type="text" name="search" class="form-control form-control-lg" placeholder="введите текст для поиска">
                <button class="ml-5 btn btn-blue"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
</div>