routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('index');

Route::get('/privacy-policy', 'HomeController@policyFile')->name('policy');
Route::get('/processing-personal-data', 'HomeController@processingPersonalDataFile')->name('processing-personal-data');
Route::get('/user-agreement', 'HomeController@userAgreementFile')->name('user-agreement');

Route::get('/faq', 'HomeController@faq')->name('faq');

Route::prefix('search')->name('search.')->group(function () {
    Route::get('', 'SearchController@index')->name('index');
});

Route::group(['prefix' => 'service', 'as' => 'service.'], function () {
    Route::get('', 'ServiceController@index')->name('index');
    Route::get('{service}', 'ServiceController@show')->name('detail');
    Route::get('{service}/detail-admin', 'ServiceController@adminDetail')->name('detail-admin')->middleware(['admin.user']);
    Route::get('{service}/form/{ticket?}', 'ServiceController@showForm')->name('form');
    Route::post('{service}/form/{ticket?}', 'ServiceController@storeForm')->name('store-form');
    Route::get('{service}/form-order', 'ServiceController@storeTicketFromOrder')->name('form-order');
    Route::post('{service}/draft/{ticket?}', 'ServiceController@storeDraft')->name('store-draft');
});

Route::prefix('discussions')->name('discussions.')->middleware('invited.forbid')->group(function () {
    Route::get('', 'DiscussionController@index')->name('index');
    Route::get('new', 'DiscussionController@create')->name('create');
    Route::get('{discussion}', 'DiscussionController@show')->name('show');
    Route::post('', 'DiscussionController@store')->name('store');
});

Route::group(['middleware' => ['auth', 'confirm.email', 'twofactor']], function () {
    Route::get('home', 'HomeController@home')->name('home');
    Route::get('profile', 'HomeController@profile')->name('profile.index');
    Route::post('profile', 'HomeController@updateProfile')->name('profile.update');
    Route::get('mesages', 'HomeController@mesages')->name('mesages.index');
    Route::get('notices', 'HomeController@notices')->name('notices.index');
    Route::get('invites', 'HomeController@invites')->name('invites.index');

    Route::get('report', 'TicketController@report')->name('report');
    Route::get('report/export', 'TicketController@ticketsExport')->name('report-export');

    //Route::prefix('search')->name('search.')->group(function () {
    //    Route::get('', 'SearchController@index')->name('index');
    //});

    Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {
        Route::get('', 'TicketController@index')->name('index');
        Route::get('/archive', 'TicketController@archive')->name('archive');
        Route::post('', 'TicketController@window')->name('window');
        Route::get('{ticket}', 'TicketController@show')->name('show');
        Route::post('{ticket}/comment', 'CommentController@store')->name('comment.new');
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('', 'OrderController@index')->name('index');
        Route::get('/create', 'OrderController@create')->name('create');
        Route::post('/update/{order}', 'OrderController@update')->name('update');
        Route::post('/store', 'OrderController@store')->name('store');
        Route::post('/store-draft', 'OrderController@storeDraft')->name('store_draft');
        Route::post('/update/{order}', 'OrderController@update')->name('update');
        Route::post('/update-draft/{order}', 'OrderController@updateDraft')->name('update_draft');
        Route::get('/{order}', 'OrderController@show')->name('show');
    });

    Route::group(['prefix' => 'api', 'namespace' => 'Api'], function () {
        Route::get('ticket', 'TicketController@index');
        Route::get('ticket/archive', 'TicketController@archive')->name('api.ticket.archive');
        Route::get('ticket/{ticket}', 'TicketController@show');
        Route::post('ticket/{ticket}/comment', 'TicketController@comment');
        Route::post('ticket/{ticket}/status', 'TicketController@changeStatus')->name('api.ticket.status');
        Route::post('tickets/comment', 'TicketController@createComments');
        Route::post('tickets/status', 'TicketController@changeStatuses');

        Route::get('order', 'OrderController@index');
        Route::post('order/filtered-users', 'OrderController@filteredUsers');
        Route::post('order/select-user', 'OrderController@selectUser');
        Route::post('order/select-category', 'OrderController@selectCategory');
        Route::post('order/select-service', 'OrderController@selectService');
        Route::get('order/{order}', 'OrderController@show');
        Route::post('order/{order}/status', 'OrderController@changeStatus')->name('api.order.status');
        Route::post('order/{order}/update-service', 'OrderController@updateService');

        Route::post('ticket/{ticket}/updateCheckList', 'TicketController@updateCheckList')->name('api.ticket.updateCheckList');

        Route::get('user', 'UserController@index');

        Route::delete('notification/{notification}', 'NotificationController@destroy')->name('api.notification.delete');
        Route::delete('invite/{invite}', 'InviteController@delete')->name('api.invite.delete');

        Route::get('invite', 'InviteController@index')->name('api.invite.index');
        Route::get('invite/available', 'InviteController@available')->name('api.invite.available');

        Route::post('affiliate/select-operators', 'AffiliateController@selectOperators');
        Route::post('affiliate/select-windows', 'AffiliateController@selectWindows');

        Route::prefix('discussions')->group(function () {
            Route::get('{discussion}/change-is-alert', 'DiscussionController@changeIsAlert')->name('changeisalert');

            Route::prefix('messages')->group(function () {
                Route::post('{discussion}', 'DiscussionController@sendMessage')->name('send');
                Route::get('{message}/read', 'DiscussionController@read')->name('read');
            });
        });

        Route::get('service-categories', 'ServiceController@getServiceCategories')->name('api.service-category');
    });
});

Route::group(['prefix' => 'admin', 'middleware' => 'confirm.email', 'twofactor'], function () {
    Voyager::routes();
    Route::put('settings', 'Voyager\SettingsController@update')->name('voyager.settings.update');
    Route::put('settings/{id}/delete_value', 'Voyager\SettingsController@delete_value')->name('voyager.settings.delete_value');

    Route::group(['middleware' => 'admin.user'], function () {
        Route::post('tickets/{ticket}/comment', 'CommentController@operatorStore')->name('operator.add.ticket');
        Route::post('tickets/{ticket}/comment/set-all-readed', 'CommentController@setAllReaded')->name('operator.read.tickets');

        Route::post('services/{service}/document', 'Api\\DocumentController@store');
        Route::put('services/{service}/document/{serviceDocument}', 'Api\\DocumentController@update');
        Route::delete('services/{service}/document/{serviceDocument}', 'Api\\DocumentController@delete');
        Route::get('services/{service}/copy', 'Voyager\\ServiceController@copy')->name('operator.copy.service');
        Route::get('supports/{support}/copy', 'Voyager\\SupportController@copy')->name('operator.copy.support');

        Route::post('services/affiliate-services', 'Api\\ServiceController@store');
    });
});

Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
    Route::get('', 'CategoryController@category')->name('index');
    Route::get('{serviceCategory}', 'CategoryController@show')->name('detail');
});

Route::get('verify-authentication/resend', 'Auth\TwoFactorController@resend')
    ->middleware('twofactor')
    ->name('verify-authentication.resend');
Route::resource('verify-authentication', 'Auth\TwoFactorController')
    ->middleware('twofactor')
    ->only(['index', 'store']);

Route::get('login/registered', 'HomeController@confirm')->middleware('auth')->name('confirm');
Route::get('login/confirm', 'HomeController@confirmation')->middleware('auth')->name('confirmation');
Route::get('auth/confirm/{user}', 'Voyager\UserController@confirmation')->name('confirmation.auth');

app/Http/Controllers/Api/Damask/TicketController.php
<?php

namespace App\Http\Controllers\Api\Damask;

use App\Models\Affiliate;
use App\Models\AffiliateService;
use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;

class TicketController extends Controller
{
    public function create(Request $request)
    {
        $operator = User::operator()->where('role_id', 1)->first();

        $coupon = $request->get('code');

        $damaskServiceCode = $request->get('operations')[0]['id'];
        $affiliate = Affiliate::where('code', $request->get('affiliate'))->first();

        $service = AffiliateService::where([
            'damask_service_code' => $damaskServiceCode,
            'affiliate_id' => $affiliate->id,
        ])->first()->service;

        $order = Order::create([
            'user_id' => $operator->id,
            'service_id' => $service->id,
            'affiliate_id' => $affiliate->id,
            'coupon' => $coupon,
            'is_damask' => true,
            'operator_id' => $operator->id,
            'status' => Order::STATUSES['DRAFT'],
        ]);

        return $order;
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Models\Affiliate;
use App\Models\Comment;
use App\Exports\TicketsExport;
use App\Http\Resources\AffiliateResourse;
use App\Http\Resources\WindowResource;
use App\Services\TicketService;
use App\Models\Ticket;
use App\Models\User;
use App\Models\Window;
use Illuminate\Contracts\Pagination\Paginator;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class TicketController extends Controller
{
    /**
     * @var TicketService
     */
    protected $ticketService;

    /**
     * TicketController constructor.
     *
     * @param  TicketService  $ticketService
     */
    public function __construct(TicketService $ticketService)
    {
        $this->ticketService = $ticketService;
    }

    /**
     * @param  Request  $request
     * @return array|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $tickets = $this->ticketService->getTicketList($request);

        if ($tickets instanceof Paginator) {
            return view('tickets.index', compact('tickets'));
        }

        $tickets['ticketFrom'] = Ticket::CREATED_FROM;

        return view('tickets.operator-lk', $tickets);
    }

    /**
     * @param  Request  $request
     * @return array|\Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function archive(Request $request)
    {
        $tickets = $this->ticketService->getTicketList($request, true);

        if ($tickets instanceof Paginator) {
            return view('tickets.index', compact('tickets'));
        }

        $tickets['ticketFrom'] = Ticket::CREATED_FROM;

        return view('tickets.operator-lk', $tickets);
    }

    /**
     * @return array|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function report(Request $request)
    {
        /** @var User $user */
        $user = auth()->user();

        if ($user->isNotRegularUser()) {
            $affiliates = AffiliateResourse::collection(Affiliate::all());
            $windows = WindowResource::collection(Window::all());
            $tickets = Ticket::getFilteredByRequestTicketsReport($request);

            return view('reports.index', compact('tickets', 'affiliates', 'windows'));
        }

        $tickets = Ticket::getFilteredByRequestTicketsReportForRegularUser($request);

        return view('reports.index', compact('tickets'));
    }

    public function ticketsExport(Request $request)
    {
        /** @var User $user */
        $user = auth()->user();

        $tickets = $user->isNotRegularUser()
            ? Ticket::getFilteredByRequestTicketsReport($request)
            : Ticket::getFilteredByRequestTicketsReportForRegularUser($request);

        return Excel::download(new TicketsExport(compact('tickets')), 'tickets.xlsx');
    }

    /**
     * @param  Ticket  $ticket
     * @return array|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Ticket $ticket)
    {
        $this->authorize('show-ticket', $ticket->formResult->user->id);

        $ticket->load(['formResult.form.service.documents', 'comments.user', 'checkList']);

        /** @var User $user */
        $user = auth()->user();

        if ($user->role->name === 'operator' || $user->role->name === 'admin') {
            $affiliates = AffiliateResourse::collection(Affiliate::all());
            $windows = WindowResource::collection(Window::all());

            $response = view('tickets.operator-lk', [
                'tickets' => [],
                'affiliates' => $affiliates,
                'windows' => $windows,
                'ticketFrom' => Ticket::CREATED_FROM,
                'colorIndicationCounts' => [],
            ]);
        } else {
            $response = view('tickets.detail', compact('ticket'));
        }

        Comment::query()
            ->where('ticket_id', '=', $ticket->id)
            ->where('user_id', '<>', auth()->id())
            ->update([
                'status' => Comment::STATUS_READED,
            ]);

        return $response;
    }

    /**
     * @param  Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function window(Request $request)
    {
        if ($request->has('window_id')) {
            $window = Window::query()
                ->where('id', '=', $request->input('window_id'))
                ->first();

            if (! is_null($window)) {
                session()->put('window', $window);
            }
        }

        return response()->json([]);
    }
}

resources/views/tickets/index.blade.php
@extends('layouts.site')

@section('title')
    Мои заявки
@endsection

@section('content')
    <div class="container">
        @if(session('formSend') === 'success')
            <div id="ticketadd-alert" class="alert alert-success alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                    Заявка успешно создана!
            </div>
        @endif
        <h1 class="mb-4">Мои заявки</h1>
        @forelse($tickets as $ticket)
            <div class="mb-4 block p-4 shadow-sm">
                <div class="d-flex justify-content-between">
                    <div class="text-muted fs-6">
                        <small>№{{ $ticket->id }} от {{ $ticket->created_at ? $ticket->created_at->format('d.m.Y, H:i'): 'Неизвестно' }}</small>
                    </div>
                    <div class="mb-2 text-end">
                        <span class="badge rounded-pill badge-corall w-auto">{{ __("ticket.status.$ticket->status") }}</span>
                    </div>
                </div>
                <div class="d-flex mb-3">
                    @if ($ticket->status === \App\Models\Ticket::STATUS_DRAFT || $ticket->status === \App\Models\Ticket::STATUS_CLIENT_WRITE)
                        <h5>{{ $ticket->formResult->form->service->name }}</h5>
                    @else
                        <h5><a href="{{ route('ticket.show', $ticket) }}">
                            {{ $ticket->formResult->form->service->name }}
                        </a></h5>
                    @endif
                </div>
                @if (!is_null($ticket->fact_end_date))
                    <div class="d-flex">
                        Дата завершения: {{ $ticket->fact_end_date->format('d.m.Y') }}
                    </div>
                @endif
                @if ($ticket->status === \App\Models\Ticket::STATUS_INVITE && !is_null($ticket->invite))
                    <div class="d-flex">
                        Приглашение назначено на {{ $ticket->invite->invite_time->format('d.m.Y H:i') }} в {{ @$ticket->invite->window->name }} {!! @$ticket->invite->window->affiliate->description !!}
                    </div>
                @endif

                @if ($ticket->status === \App\Models\Ticket::STATUS_NEW)
                    <div class="d-block button-more text-end mb-3">
                        <button value="{{$ticket->id}}" type="button" class="btn btn-corall rounded-pill px-4 popup-open" data-bs-toggle="modal" data-bs-target="#cancelmodal">Запросить отмену</button>
                        <!-- Modal -->
                        <div class="modal fade" id="cancelmodal" tabindex="-1" aria-labelledby="cancelmodallLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Подтвердите запрос на отмену заявки</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Вы действительно хотите запросить отмену заявки №{{ $ticket->id }} на получение услуги "{{ $ticket->formResult->form->service->name }}"?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-corall rounded-pill px-4" data-bs-dismiss="modal">Отменить</button>
                                        <form  method="POST"  action="{{ route('api.ticket.status', $ticket) }}">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="status" value="{{ \App\Models\Ticket::STATUS_CANCEL_REQUEST }}">
                                            <button type="submit" class="btn btn-coral">Подтвердить</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endif
                @if (in_array($ticket->status, [\App\Models\Ticket::STATUS_DRAFT, \App\Models\Ticket::STATUS_NEED_DATA, \App\Models\Ticket::STATUS_CLIENT_WRITE]))
                    <div class="d-block button-more text-end mb-3">
                        <a class="btn btn-corall rounded-pill px-4" href="{{ route('service.form', [$ticket->formResult->form->service, $ticket]) }}">
                            Редактировать черновик
                        </a>
                    </div>
                @endif
                <div class="d-block button-more text-end">
                    <a href="{{ route('ticket.show', $ticket) }}" class="btn btn-blue rounded-pill px-4">Подробнее</a>
                </div>
            </div>
        @empty
            <div class="content">
                <p>У вас пока нет заявок</p>
            </div>
        @endforelse

        {{ $tickets->links() }}
    </div>

    <script>
      $(function(){
        window.setTimeout(function(){
          $('#ticketadd-alert').alert('close');
        },3000);
      });
    </script>

    <script>
        $(document).ready(function() {
            $('#table_tickets').dataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.11.1/i18n/ru.json"
                },
                "order": [[ 0, "desc" ]]
            });
        });
    </script>

@endsection

resources/views/tickets/operator-lk.blade.php
@extends('layouts.site')

@section('title')
    Список заявок
@endsection

@section('content')
    <div class="container-fluid">
        <div id="app"></div>
    </div>
@endsection

@section('js')
    <script>
        window.affiliates = {!! json_encode($affiliates) !!};
        window.tickets = {!! json_encode($tickets) !!};
        window.user = {!! json_encode(auth()->user()) !!};
        window.windows = {!! json_encode($windows) !!};
        window.currentWindow = {!! json_encode(session()->get('window')) !!};
        window.ticketFrom = {!! json_encode($ticketFrom) !!};
        window.colorIndicationCounts = {!! json_encode($colorIndicationCounts) !!};
    </script>
    <script src="{{ asset('js/operator-lk.js') }}"></script>
@endsection