routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('index');

Route::get('/privacy-policy', 'HomeController@policyFile')->name('policy');
Route::get('/processing-personal-data', 'HomeController@processingPersonalDataFile')->name('processing-personal-data');
Route::get('/user-agreement', 'HomeController@userAgreementFile')->name('user-agreement');

Route::get('/faq', 'HomeController@faq')->name('faq');

Route::prefix('search')->name('search.')->group(function () {
    Route::get('', 'SearchController@index')->name('index');
});

Route::group(['prefix' => 'service', 'as' => 'service.'], function () {
    Route::get('', 'ServiceController@index')->name('index');
    Route::get('{service}', 'ServiceController@show')->name('detail');
    Route::get('{service}/detail-admin', 'ServiceController@adminDetail')->name('detail-admin')->middleware(['admin.user']);
    Route::get('{service}/form/{ticket?}', 'ServiceController@showForm')->name('form');
    Route::post('{service}/form/{ticket?}', 'ServiceController@storeForm')->name('store-form');
    Route::get('{service}/form-order', 'ServiceController@storeTicketFromOrder')->name('form-order');
    Route::post('{service}/draft/{ticket?}', 'ServiceController@storeDraft')->name('store-draft');
});

Route::prefix('discussions')->name('discussions.')->middleware('invited.forbid')->group(function () {
    Route::get('', 'DiscussionController@index')->name('index');
    Route::get('new', 'DiscussionController@create')->name('create');
    Route::get('{discussion}', 'DiscussionController@show')->name('show');
    Route::post('', 'DiscussionController@store')->name('store');
});

Route::group(['middleware' => ['auth', 'confirm.email', 'twofactor']], function () {
    Route::get('home', 'HomeController@home')->name('home');
    Route::get('profile', 'HomeController@profile')->name('profile.index');
    Route::post('profile', 'HomeController@updateProfile')->name('profile.update');
    Route::get('mesages', 'HomeController@mesages')->name('mesages.index');
    Route::get('notices', 'HomeController@notices')->name('notices.index');
    Route::get('invites', 'HomeController@invites')->name('invites.index');

    Route::get('report', 'TicketController@report')->name('report');
    Route::get('report/export', 'TicketController@ticketsExport')->name('report-export');

    //Route::prefix('search')->name('search.')->group(function () {
    //    Route::get('', 'SearchController@index')->name('index');
    //});

    Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {
        Route::get('', 'TicketController@index')->name('index');
        Route::get('/archive', 'TicketController@archive')->name('archive');
        Route::post('', 'TicketController@window')->name('window');
        Route::get('{ticket}', 'TicketController@show')->name('show');
        Route::post('{ticket}/comment', 'CommentController@store')->name('comment.new');
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('', 'OrderController@index')->name('index');
        Route::get('/create', 'OrderController@create')->name('create');
        Route::post('/update/{order}', 'OrderController@update')->name('update');
        Route::post('/store', 'OrderController@store')->name('store');
        Route::post('/store-draft', 'OrderController@storeDraft')->name('store_draft');
        Route::post('/update/{order}', 'OrderController@update')->name('update');
        Route::post('/update-draft/{order}', 'OrderController@updateDraft')->name('update_draft');
        Route::get('/{order}', 'OrderController@show')->name('show');
    });

    Route::group(['prefix' => 'api', 'namespace' => 'Api'], function () {
        Route::get('ticket', 'TicketController@index');
        Route::get('ticket/archive', 'TicketController@archive')->name('api.ticket.archive');
        Route::get('ticket/{ticket}', 'TicketController@show');
        Route::post('ticket/{ticket}/comment', 'TicketController@comment');
        Route::post('ticket/{ticket}/status', 'TicketController@changeStatus')->name('api.ticket.status');
        Route::post('tickets/comment', 'TicketController@createComments');
        Route::post('tickets/status', 'TicketController@changeStatuses');

        Route::get('order', 'OrderController@index');
        Route::post('order/filtered-users', 'OrderController@filteredUsers');
        Route::post('order/select-user', 'OrderController@selectUser');
        Route::post('order/select-category', 'OrderController@selectCategory');
        Route::post('order/select-service', 'OrderController@selectService');
        Route::get('order/{order}', 'OrderController@show');
        Route::post('order/{order}/status', 'OrderController@changeStatus')->name('api.order.status');
        Route::post('order/{order}/update-service', 'OrderController@updateService');

        Route::post('ticket/{ticket}/updateCheckList', 'TicketController@updateCheckList')->name('api.ticket.updateCheckList');

        Route::get('user', 'UserController@index');

        Route::delete('notification/{notification}', 'NotificationController@destroy')->name('api.notification.delete');
        Route::delete('invite/{invite}', 'InviteController@delete')->name('api.invite.delete');

        Route::get('invite', 'InviteController@index')->name('api.invite.index');
        Route::get('invite/available', 'InviteController@available')->name('api.invite.available');

        Route::post('affiliate/select-operators', 'AffiliateController@selectOperators');
        Route::post('affiliate/select-windows', 'AffiliateController@selectWindows');

        Route::prefix('discussions')->group(function () {
            Route::get('{discussion}/change-is-alert', 'DiscussionController@changeIsAlert')->name('changeisalert');

            Route::prefix('messages')->group(function () {
                Route::post('{discussion}', 'DiscussionController@sendMessage')->name('send');
                Route::get('{message}/read', 'DiscussionController@read')->name('read');
            });
        });

        Route::get('service-categories', 'ServiceController@getServiceCategories')->name('api.service-category');
    });
});

Route::group(['prefix' => 'admin', 'middleware' => 'confirm.email', 'twofactor'], function () {
    Voyager::routes();
    Route::put('settings', 'Voyager\SettingsController@update')->name('voyager.settings.update');
    Route::put('settings/{id}/delete_value', 'Voyager\SettingsController@delete_value')->name('voyager.settings.delete_value');

    Route::group(['middleware' => 'admin.user'], function () {
        Route::post('tickets/{ticket}/comment', 'CommentController@operatorStore')->name('operator.add.ticket');
        Route::post('tickets/{ticket}/comment/set-all-readed', 'CommentController@setAllReaded')->name('operator.read.tickets');

        Route::post('services/{service}/document', 'Api\\DocumentController@store');
        Route::put('services/{service}/document/{serviceDocument}', 'Api\\DocumentController@update');
        Route::delete('services/{service}/document/{serviceDocument}', 'Api\\DocumentController@delete');
        Route::get('services/{service}/copy', 'Voyager\\ServiceController@copy')->name('operator.copy.service');
        Route::get('supports/{support}/copy', 'Voyager\\SupportController@copy')->name('operator.copy.support');

        Route::post('services/affiliate-services', 'Api\\ServiceController@store');
    });
});

Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
    Route::get('', 'CategoryController@category')->name('index');
    Route::get('{serviceCategory}', 'CategoryController@show')->name('detail');
});

Route::get('verify-authentication/resend', 'Auth\TwoFactorController@resend')
    ->middleware('twofactor')
    ->name('verify-authentication.resend');
Route::resource('verify-authentication', 'Auth\TwoFactorController')
    ->middleware('twofactor')
    ->only(['index', 'store']);

Route::get('login/registered', 'HomeController@confirm')->middleware('auth')->name('confirm');
Route::get('login/confirm', 'HomeController@confirmation')->middleware('auth')->name('confirmation');
Route::get('auth/confirm/{user}', 'Voyager\UserController@confirmation')->name('confirmation.auth');

resources/views/menu/menu.blade.php
<nav class="navbar navbar-expand-xl navbar-light p-0">
    <div class="container-fluid d-flex align-items-baseline">
        <a class="navbar-brand" href="/">
            <!--<img src="{{ setting('site.logo') }}" alt="logo" height="82px">-->
            <img class="logo" src="/images/new_logo.png" alt="logo" >
        </a>
        <div class="justify-content-end">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="offcanvas offcanvas-end flex-grow-1" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
                    @auth
                        {{ auth()->user()->name }} {{ auth()->user()->firstname }}
                    @else
                        Меню
                    @endauth
                </h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body justify-content-between align-items-center">
                {{ menu('site') }}
                @auth
                    @if (in_array(auth()->user()->role->name, ['admin', 'operator']) && auth()->user()->is_confirmed && !auth()->user()->two_factor_code)
                        {{ menu('operator') }}
                    @elseif(auth()->user()->is_confirmed && !auth()->user()->two_factor_code)
                        {{ menu('user') }}
                    @endif
                @endauth
                @auth
                    @if (!auth()->user()->two_factor_code && auth()->user()->is_confirmed)
                    <ul class="navbar-nav justify-content-end mt-0 align-items-center ml-3">

                        @php
                            $newMessagesCount = auth()->user()->newMessagesCount;
                            $notifications = auth()->user()->notificationsCount;
                            $invites = auth()->user()->invitesCount;
                            $newDiscussionsMessagesCount = auth()->user()->newDiscussionsMessagesCount;
                        @endphp
                        @if(auth()->user()->can('browse_admin'))
                            <li class="nav-item my-2"><a class="menu-link mx-3" href="{{ route('voyager.dashboard') }}"> {{ auth()->user()->name }} {{ auth()->user()->firstname }}</a></li>
                        @elseif (in_array(auth()->user()->role->name, ['operator']))
                            <li class="nav-item my-2"><a class="menu-link mx-3" href="{{ route('voyager.dashboard') }}">{{ auth()->user()->name }} {{ auth()->user()->firstname }}</a></li>
                        @endif
                        @if (!in_array(auth()->user()->role->name, ['admin', 'operator']))
                            <li class="nav-item my-2"><a class="menu-link mx-3" href="{{ route('profile.index') }}">{{ auth()->user()->name }} {{ auth()->user()->firstname }}</a></li>
                        @endif
                        <li class="nav-item my-2">
                            <a class="menu-link d-flex mx-3" href="{{ route('logout') }}"
                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            Выйти
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </li>
                    </ul>
                    <div class="row align-items-center text-center my-2">
                        <div class="col-12">
                            <a class="btn position-relative btn-outline-blue btn-menu mx-1" href="{{ route('notices.index') }}" alt="Уведомления" data-toggle="tooltip" data-placement="bottom" title="Уведомления">
                                <i class="fa fa-bell"></i>
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill @if($notifications > 0) badge-corall @else badge-outline-blue @endif">@if($notifications > 0) {{ $notifications }} @elseif($notifications > 99) 99+ @else {{ $notifications }} @endif</span>
                            </a>
                            <a class="btn position-relative btn-outline-blue btn-menu mx-1" href="{{ route('mesages.index') }}" alt="Сообщения" data-toggle="tooltip" data-placement="bottom" title="Комментарии">
                                <i class="fa fa-envelope-open"></i>
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill @if($newMessagesCount > 0) badge-corall @else badge-outline-blue @endif">@if($newMessagesCount > 0) {{ $newMessagesCount }} @elseif($newMessagesCount > 99) 99+ @else {{ $newMessagesCount }} @endif</span>
                            </a>
                            <a class="btn position-relative btn-outline-blue btn-menu mx-1" href="{{ route('invites.index') }}" alt="Приглашения" data-toggle="tooltip" data-placement="bottom" title="Приглашения">
                                <i class="fa fa-calendar"></i>
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill @if($invites > 0) badge-corall @else badge-outline-blue @endif">@if($invites > 0) {{ $invites }} @elseif ($invites > 99) 99+ @else {{ $invites }} @endif</span>
                            </a>
                            <a class="btn position-relative btn-outline-blue btn-menu mx-1" href="{{ route('discussions.index') }}" alt="Обращения" data-toggle="tooltip" data-placement="bottom" title="Обращения">
                                <i class="fa fa-comments"></i>
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill @if($newDiscussionsMessagesCount > 0) badge-corall @else badge-outline-blue @endif">@if($newDiscussionsMessagesCount > 0) {{ $newDiscussionsMessagesCount }} @elseif ($newDiscussionsMessagesCount > 99) 99+ @else {{ $newDiscussionsMessagesCount }} @endif</span>
                            </a>
                        </div>
                    </div>
                    @else
                        <ul class="navbar-nav justify-content-end mt-0 align-items-center ml-3">
                        <li class="nav-item my-0">
                            <a class="position-relative btn-menu mx-1" href="{{ route('logout') }}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                Сменить аккаунт
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </li>
                        </ul>
                    @endif
                @else
                    <ul class="navbar-nav justify-content-end mt-0 align-items-center">
                        <button class="d-block btn btn-corall px-5 rounded-pill mx-3 my-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvaslogin" aria-controls="offcanvaslogin">Вход</button>
                    </ul>
                @endauth
            </div>
        </div>
    </div>
</nav>

resources/views/menu/menuapp.blade.php
<nav class="navbar navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'МФЦБ') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>                            
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>