routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('index');

Route::get('/privacy-policy', 'HomeController@policyFile')->name('policy');
Route::get('/processing-personal-data', 'HomeController@processingPersonalDataFile')->name('processing-personal-data');
Route::get('/user-agreement', 'HomeController@userAgreementFile')->name('user-agreement');

Route::get('/faq', 'HomeController@faq')->name('faq');

Route::prefix('search')->name('search.')->group(function () {
    Route::get('', 'SearchController@index')->name('index');
});

Route::group(['prefix' => 'service', 'as' => 'service.'], function () {
    Route::get('', 'ServiceController@index')->name('index');
    Route::get('{service}', 'ServiceController@show')->name('detail');
    Route::get('{service}/detail-admin', 'ServiceController@adminDetail')->name('detail-admin')->middleware(['admin.user']);
    Route::get('{service}/form/{ticket?}', 'ServiceController@showForm')->name('form');
    Route::post('{service}/form/{ticket?}', 'ServiceController@storeForm')->name('store-form');
    Route::get('{service}/form-order', 'ServiceController@storeTicketFromOrder')->name('form-order');
    Route::post('{service}/draft/{ticket?}', 'ServiceController@storeDraft')->name('store-draft');
});

Route::prefix('discussions')->name('discussions.')->middleware('invited.forbid')->group(function () {
    Route::get('', 'DiscussionController@index')->name('index');
    Route::get('new', 'DiscussionController@create')->name('create');
    Route::get('{discussion}', 'DiscussionController@show')->name('show');
    Route::post('', 'DiscussionController@store')->name('store');
});

Route::group(['middleware' => ['auth', 'confirm.email', 'twofactor']], function () {
    Route::get('home', 'HomeController@home')->name('home');
    Route::get('profile', 'HomeController@profile')->name('profile.index');
    Route::post('profile', 'HomeController@updateProfile')->name('profile.update');
    Route::get('mesages', 'HomeController@mesages')->name('mesages.index');
    Route::get('notices', 'HomeController@notices')->name('notices.index');
    Route::get('invites', 'HomeController@invites')->name('invites.index');

    Route::get('report', 'TicketController@report')->name('report');
    Route::get('report/export', 'TicketController@ticketsExport')->name('report-export');

    //Route::prefix('search')->name('search.')->group(function () {
    //    Route::get('', 'SearchController@index')->name('index');
    //});

    Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {
        Route::get('', 'TicketController@index')->name('index');
        Route::get('/archive', 'TicketController@archive')->name('archive');
        Route::post('', 'TicketController@window')->name('window');
        Route::get('{ticket}', 'TicketController@show')->name('show');
        Route::post('{ticket}/comment', 'CommentController@store')->name('comment.new');
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('', 'OrderController@index')->name('index');
        Route::get('/create', 'OrderController@create')->name('create');
        Route::post('/update/{order}', 'OrderController@update')->name('update');
        Route::post('/store', 'OrderController@store')->name('store');
        Route::post('/store-draft', 'OrderController@storeDraft')->name('store_draft');
        Route::post('/update/{order}', 'OrderController@update')->name('update');
        Route::post('/update-draft/{order}', 'OrderController@updateDraft')->name('update_draft');
        Route::get('/{order}', 'OrderController@show')->name('show');
    });

    Route::group(['prefix' => 'api', 'namespace' => 'Api'], function () {
        Route::get('ticket', 'TicketController@index');
        Route::get('ticket/archive', 'TicketController@archive')->name('api.ticket.archive');
        Route::get('ticket/{ticket}', 'TicketController@show');
        Route::post('ticket/{ticket}/comment', 'TicketController@comment');
        Route::post('ticket/{ticket}/status', 'TicketController@changeStatus')->name('api.ticket.status');
        Route::post('tickets/comment', 'TicketController@createComments');
        Route::post('tickets/status', 'TicketController@changeStatuses');

        Route::get('order', 'OrderController@index');
        Route::post('order/filtered-users', 'OrderController@filteredUsers');
        Route::post('order/select-user', 'OrderController@selectUser');
        Route::post('order/select-category', 'OrderController@selectCategory');
        Route::post('order/select-service', 'OrderController@selectService');
        Route::get('order/{order}', 'OrderController@show');
        Route::post('order/{order}/status', 'OrderController@changeStatus')->name('api.order.status');
        Route::post('order/{order}/update-service', 'OrderController@updateService');

        Route::post('ticket/{ticket}/updateCheckList', 'TicketController@updateCheckList')->name('api.ticket.updateCheckList');

        Route::get('user', 'UserController@index');

        Route::delete('notification/{notification}', 'NotificationController@destroy')->name('api.notification.delete');
        Route::delete('invite/{invite}', 'InviteController@delete')->name('api.invite.delete');

        Route::get('invite', 'InviteController@index')->name('api.invite.index');
        Route::get('invite/available', 'InviteController@available')->name('api.invite.available');

        Route::post('affiliate/select-operators', 'AffiliateController@selectOperators');
        Route::post('affiliate/select-windows', 'AffiliateController@selectWindows');

        Route::prefix('discussions')->group(function () {
            Route::get('{discussion}/change-is-alert', 'DiscussionController@changeIsAlert')->name('changeisalert');

            Route::prefix('messages')->group(function () {
                Route::post('{discussion}', 'DiscussionController@sendMessage')->name('send');
                Route::get('{message}/read', 'DiscussionController@read')->name('read');
            });
        });

        Route::get('service-categories', 'ServiceController@getServiceCategories')->name('api.service-category');
    });
});

Route::group(['prefix' => 'admin', 'middleware' => 'confirm.email', 'twofactor'], function () {
    Voyager::routes();
    Route::put('settings', 'Voyager\SettingsController@update')->name('voyager.settings.update');
    Route::put('settings/{id}/delete_value', 'Voyager\SettingsController@delete_value')->name('voyager.settings.delete_value');

    Route::group(['middleware' => 'admin.user'], function () {
        Route::post('tickets/{ticket}/comment', 'CommentController@operatorStore')->name('operator.add.ticket');
        Route::post('tickets/{ticket}/comment/set-all-readed', 'CommentController@setAllReaded')->name('operator.read.tickets');

        Route::post('services/{service}/document', 'Api\\DocumentController@store');
        Route::put('services/{service}/document/{serviceDocument}', 'Api\\DocumentController@update');
        Route::delete('services/{service}/document/{serviceDocument}', 'Api\\DocumentController@delete');
        Route::get('services/{service}/copy', 'Voyager\\ServiceController@copy')->name('operator.copy.service');
        Route::get('supports/{support}/copy', 'Voyager\\SupportController@copy')->name('operator.copy.support');

        Route::post('services/affiliate-services', 'Api\\ServiceController@store');
    });
});

Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
    Route::get('', 'CategoryController@category')->name('index');
    Route::get('{serviceCategory}', 'CategoryController@show')->name('detail');
});

Route::get('verify-authentication/resend', 'Auth\TwoFactorController@resend')
    ->middleware('twofactor')
    ->name('verify-authentication.resend');
Route::resource('verify-authentication', 'Auth\TwoFactorController')
    ->middleware('twofactor')
    ->only(['index', 'store']);

Route::get('login/registered', 'HomeController@confirm')->middleware('auth')->name('confirm');
Route::get('login/confirm', 'HomeController@confirmation')->middleware('auth')->name('confirmation');
Route::get('auth/confirm/{user}', 'Voyager\UserController@confirmation')->name('confirmation.auth');

app/Models/Discussion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Storage;

class Discussion extends Model
{
    public const STATUS_CLOSE = 0;

    public const STATUS_OPEN = 1;

    protected $fillable = [
        'name',
        'text',
        'filenames',
        'is_alert',
        'user_owner_id',
        'user_recipient_id',
    ];

    protected $casts = [
        'is_alert' => 'bool',
    ];

    public function setIsAlert($is_alert)
    {
        $this->update(
            [
                'is_alert' => $is_alert,
            ]
        );
    }

    public function messages(): HasMany
    {
        return $this->hasMany(DiscussionMessage::class, 'discussion_group_id');
    }

    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_owner_id');
    }

    public function recipient(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_recipient_id');
    }

    public function getUnreadAttribute()
    {
        $user = auth()->user();

        return $this->messages()->getQuery()
                ->where('user_owner_id', '!=', $user->id)
                ->where('status', DiscussionMessage::STATUS_UNREAD)
                ->get();
    }

    public function getFilesUrlsAttribute()
    {
        $filesUrls = [];
        $files = json_decode($this->filenames);

        if ($files) {
            foreach ($files as $file) {
                $filesUrls[$file->name] = Storage::url($file->download_link);
            }
        }

        return $filesUrls;
    }
}

app/Http/Controllers/Api/DiscussionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Discussion;
use App\Models\DiscussionMessage;
use App\Http\Controllers\Controller;
use App\Http\Requests\Discussion\MessageRequest;
use App\Http\Resources\DiscussionMessageResource;
use App\Services\FileService;
use Illuminate\Http\Request;

class DiscussionController extends Controller
{
    /**
     * @var FileService
     */
    private $service;

    public function __construct(FileService $service)
    {
        $this->service = $service;
    }

    public function read(DiscussionMessage $message)
    {
        $message->setStatus(DiscussionMessage::STATUS_READ);

        return response()->json(['message' => DiscussionMessageResource::make($message)]);
    }

    public function changeIsAlert(Discussion $discussion)
    {
        $discussion->setIsAlert(Discussion::STATUS_CLOSE);

        return response('OK', 200);
    }

    public function paginatedIndex(Request $request)
    {
        $user = auth()->user();

        $discussions = Discussion::withCount('messages');

        if (in_array($user->role->name, ['user', 'invited'])) {
            $discussions = $discussions->where('user_owner_id', $user->id);
        } else {
            $discussions = $discussions->where('user_recipient_id', $user->id);
        }

        $discussions = $discussions->paginate(
            $request->get('per_page', 50),
        );

        return response()->json($discussions);
    }

    public function sendMessage(MessageRequest $request, Discussion $discussion)
    {
        $validatedData = $request->validated();

        $files = $validatedData['files'] ?? null;
        $loadedFiles = [];

        if ($files) {
            $filenames = $this->service->saveFiles('discussions', $files);

            foreach ($filenames as $filename) {
                $loadedFiles[] = [
                    'name' => $filename,
                    'original_name' => $filename,
                    'download_link' => 'discussions/'.$filename,
                ];
            }
        }

        $message = $discussion->messages()->create([
            'text' => $validatedData['text'] ?? null,
            'filenames' => $loadedFiles,
            'user_owner_id' => auth()->user()->id,
        ]);

        return response()->json(['message' => DiscussionMessageResource::make($message)]);
    }
}

app/Http/Controllers/DiscussionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Discussion;
use App\Models\DiscussionMessage;
use App\Http\Requests\Discussion\AlertedRequest;
use App\Http\Requests\Discussion\DiscussionRequest;
use App\Http\Resources\Discussion\UserResource;
use App\Http\Resources\DiscussionResource;
use App\Services\FileService;
use Illuminate\Http\Request;

class DiscussionController extends Controller
{
    private $service;

    public function __construct(FileService $service)
    {
        $this->service = $service;
    }

    public function index(Request $request)
    {
        $user = auth()->user();

        $discussions = Discussion::withCount(['messages' => function ($query) use ($user) {
            return $query->where('user_owner_id', '!=', $user->id)
                    ->where('status', DiscussionMessage::STATUS_UNREAD);
        }]);

        if ($user->role->name == 'user') {
            $discussions = $discussions->where('user_owner_id', $user->id)->orderBy('created_at', 'desc');
        } else {
            $discussions = $discussions->where('user_recipient_id', $user->id)->orderBy('created_at', 'desc');
        }

        $discussions = $discussions->paginate(
            $request->get('per_page', 50)
        );

        return view('discussions.index', compact('discussions'));
    }

    public function create(AlertedRequest $request)
    {
        $data = $request->validated();
        $head = $data['name'] ?? '';
        $isAlert = $data['is_alert'] ?? false;

        return view('discussions.create', compact('head', 'isAlert'));
    }

    public function store(DiscussionRequest $request)
    {
        $data = $request->validated();

        $files = $data['files'] ?? null;
        $loadedFiles = [];

        if ($files) {
            $filenames = $this->service->saveFiles('discussions', $files);

            foreach ($filenames as $filename) {
                $loadedFiles[] = [
                    'name' => $filename,
                    'original_name' => $filename,
                    'download_link' => 'discussions/'.$filename,
                ];
            }
        }

        $data['filenames'] = json_encode($loadedFiles);
        $data['is_alert'] = isset($data['is_alert']);

        $discussion = Discussion::create($data);

        return redirect()->route('discussions.show', $discussion);
    }

    public function show(Discussion $discussion)
    {
        $discussion = DiscussionResource::make($discussion);
        $user = UserResource::make(auth()->user());

        return view('discussions.operator-lk', compact('discussion', 'user'));
    }
}

resources/views/discussions/create.blade.php
@extends('layouts.site')

@section('title')
    Создание нового обращения
@endsection

@section('content')
    <div class="container">
        <h1 class="mb-4">Новое обращение</h1>
        <div class="row">
            <div class="col-md-9">
                <div class="content p-4 shadow-sm">
                    <form id="kt_inbox_reply_form" action="{{ route('discussions.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                        <div class="d-block">
                            @if ($isAlert)
                                <input type="hidden" name="is_alert" value="true">
                            @endif
                            <div class="mb-3">
                                <input class="form-control border-0" name="name" placeholder="Введите тему обращения" value="{{ $head ?? '' }}" required>
                            </div>
                            <hr>
                            <textarea class="form-control  border-0" name="text" placeholder="Введите текст сообщения" style="height: 200px;" required></textarea>
                        </div>
                        <div class="d-flex align-items-center mt-5">
                            <div class="mb-3">                        
                                <input type="file" multiple id="files_id" class="form-control custom-file-input" name="files[]" />
                                <span id="files-error"></span>
                            </div>
                            @error('files.*')
                                <span class="label label-light-danger font-weight-bold label-inline">{{ $message }}</span>
                            @enderror
                        </div>
                        <hr>
                        <div class="text-end">
                                <button type="submit" class="btn btn-blue">Отправить</button>
                            </div>
                    </form>
                </div>
            </div>
            <div class="col-md-3">
                <div class="row">
                    <div class="col-md-12">
                        <div class="side card mb-3">
                            <div class="card-header">
                                <h5>Часто задаваемые вопросы</h5>
                            </div>
                            <div class="card-body">
                                Вы можете ознакомится с наиболее часто задаваемыми вопросами в разделе
                                <a href=" {{ route('faq') }} ">Часто задоваемые вопросы</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        </div>
    </div>
@endsection

@section('js')
    <script>
        $('#files_id').change(function (e) {
            var resultingSize = 0;
            let fileNames = '';

            this.files.forEach(element => {
                if (this.value === "") {
                    return;
                }

                fileNames += element.name + '<br>';

                if (element.size > 2097152) {
                    this.value = "";

                    $('#files-error').text("Размер одного файла не должен превышать 2 мегабайт");

                    return;
                }

                resultingSize += element.size;

                let maxSize = 5242880;

                if (maxSize < resultingSize) {
                    this.value = "";

                    $('#files-error').text("Общий размер файлов не должен превышать 5 мегабайт");

                    return;
                }
            });

            $('#files-error').html(fileNames);
        });
    </script>
@endsection

resources/views/discussions/index.blade.php
@extends('layouts.site')

@section('title')
    Обращения
@endsection

@section('content')
    <div class="container">
        <div class="mb-4 d-flex align-items-center justify-content-between">
            <div class="title">    
                <h1>Обращения</h1>
            </div>
            <div class="text-end">
                @if (!in_array(auth()->user()->role->name, ['admin', 'operator']))
                    <a href="{{ route('discussions.create') }}" class="btn btn-blue" role="button">
                        Cоздать обращение
                    </a>
                @endif
            </div>
        </div>
            @forelse($discussions as $discussion)
                @php
                    $isRead = $discussion->messages_count > 0 ? "font-weight-bolder" : "";
                @endphp
                <div class="mb-4 block shadow-sm p-4">
                    <div class="d-flex justify-content-between">
                        <div class="text-muted fs-6">
                            <small>№{{ $discussion->id }} от</small> <small>{{ $discussion->updated_at->format('d.m.Y, H:m:s') }}</small>
                        </div>
                        <div class="mb-2 text-end">                                
                            @if ($discussion->messages_count > 0)                     
                                <span class="badge rounded-pill badge-corall w-auto">Непрочитано {{ $discussion->messages_count }}</span>
                            @endif
                            @if ($discussion->is_alert)                           
                                <span class="badge rounded-pill badge-blue w-auto">Открыто</span>
                            @else
                                <span class="badge rounded-pill badge-light w-auto">Закрыто</span>
                            @endif
                        </div>
                    </div>
                    <div class="d-flex">                            
                        <a href="{{ route('discussions.show', $discussion)}}" class="fs-5">{{ $discussion->name }}</a>
                    </div>                                           
                    <div class="d-block button-more text-end mt-3">
                        <a href="{{ route('discussions.show', $discussion)}}"><i class="fa fa-chevron-circle-right fa-2x"></i></a>
                    </div>
                </div>
            @empty
                <div class="content">
                    У вас нет сообщений
                </div>
            @endforelse                
        </div>
    </div>
@endsection

resources/views/discussions/operator-lk.blade.php
@extends('layouts.site')

@section('title')
    Обращение №{{ $discussion->id }}
@endsection

@section('content')
    <div class="container">
        <div id="app"></div>
    </div>
@endsection

@section('js')
    <script>
        window.discussion = {!! json_encode($discussion) !!};
        window.user = {!! json_encode($user) !!};
        window.csrf = $('meta[name="csrf-token"]').attr('content');
    </script>
    <script src="{{ asset('js/operator-lk.js') }}"></script>
@endsection

resources/views/discussions/show.blade.php
@extends('layouts.site')

@section('title')
    Обращение №{{ $discussion->id }}
@endsection

@section('content')
    <div class="container">
        <h1 class="mb-4">
            Обращение №{{ $discussion->id }}
        </h1>
        <div class="content p-4 shadow-sm">         
            <div class="d-flex justify-content-between mb-3">
                <div class="d-block">
                    <div class="d-block text-muted small">{{ $discussion->owner->name }} {{ $discussion->owner->firstname }}</div>            
                    <div class="d-block text-muted small">
                        {{ $discussion->created_at->format('d.m.Y, m:h') }}
                    </div>
                </div>
                <div class="d-block">
                    @if ($discussion->is_alert)    
                        <div class="mb-2 text-end">                            
                            <span class="badge rounded-pill badge-corall w-auto">Открыто</span>
                        </div>
                        @if (in_array(auth()->user()->role->name, ['admin', 'operator']))
                            <div class="btn-group" role="group">
                                <button id="dropdownAlertButton" type="button" class="btn btn-blue btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    Открыто
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownAlertButton">
                                    <li><a class="dropdown-item" href="{{ route('discussions.changeisalert', $discussion ) }}">Закрыть</a></li>
                                    <li><a class="dropdown-item" href="{{ route('discussions.changeisalert', $discussion ) }}">Закрыть и создать заявку</a></li>
                                </ul>
                            </div>
                        @endif
                    @else
                        <div class="mb-2 text-end">                            
                            <span class="badge rounded-pill badge-light w-auto">Закрыто</span>
                        </div>    
                    @endif
                </div>
            </div>
            <div class="d-flex mb-3">                     
                <h4>{{ $discussion->name }}</h4>
            </div>
            <div class="d-block">{!! $discussion->text !!}</div>
            @if (is_array($discussion->filesUrls))
                <div class="d-block align-items-center py-3">
                    @foreach ($discussion->filesUrls as $key => $url)
                        <div class="mb-1 d-flex align-items-center">
                            <a href="{{ $url }}" target="_blank"><i class="icon-xl fa fa-file-download"></i> {{ $key }}</a>
                        </div>
                    @endforeach
                </div>
            @endif
            <hr>
            @foreach ($discussion->messages as $message)
                <div class="d-flex align-items-center justify-content-between pb-3" data-inbox="message">
                    <div class="d-block">
                        <div class="d-block text-muted small">
                            {{ auth()->user()->id === $message->user_owner_id ? 'Вы' : $message->author->name }} {{ auth()->user()->id === $message->user_owner_id ? '' : $message->author->firstname }}
                        </div>
                        <div class="d-block text-muted small">
                            <div class="font-weight-bold text-muted mr-2">
                                {{ $message->created_at->format('d.m.Y, m:h') }}
                            </div>
                        </div>                        
                    </div>    
                    <div class="d-flex text-end">
                        @if ($user->id !== $message->user_owner_id && $message->status === App\Models\DiscussionMessage::STATUS_UNREAD) 
                            <div class="btn-group" role="group">
                                <button id="dropdownMenuButton" type="button" class="btn btn-blue btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    Не прочитано
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li><a class="dropdown-item" href="{{ route('discussions.read', $message) }}">Прочитано</a></li>
                                </ul>
                            </div>
                        @elseif ($message->status === App\Models\DiscussionMessage::STATUS_READ)
                            <div class="d-block text-end">
                                <div class="d-block fw-bold text-muted small">Прочитано</div>
                                <div class="d-block fw-bold text-muted small">{{ $message->updated_at->format('d.m.Y, m:h') }}</div>
                            </div>
                        @endif
                    </div>                   
                </div>                
                <div>{{ $message->text }}</div>
                @if ($message->filenames)
                    <div class="mt-2">
                        @foreach ($message->filesUrls as $key => $url)
                            <div class="mb-1 d-flex align-items-center">
                                <a href="{{ $url }}" target="_blank"><i class="icon-xl fa fa-file-download"></i> {{ $key }}</a>
                            </div>
                        @endforeach
                    </div>
                @endif
                <hr>
            @endforeach
        </div>
        @if ($discussion->is_alert)     
            <div class="content mt-5">
                <form id="kt_inbox_reply_form" action="{{ route('discussions.send', $discussion) }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="d-block">
                        <textarea placeholder="Введите сообщение ..." style="height: 100px;" name="text" class="form-control p-10" id="text"></textarea>
                    </div>
                    @error('text')
                        <span class="label label-light-danger font-weight-bold label-inline">{{ $message }}</span>
                    @enderror
                    <div class="d-flex align-items-center mt-5">                       
                        <div class="mb-3">
                            <input type="file" class="form-control custom-file-input" id="customFile" name="files[]" multiple>
                        </div>
                        @error('files.*')
                            <span class="label label-light-danger font-weight-bold label-inline">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="text-end">
                        <button type="submit" class="btn btn-blue btn-shadow font-weight-bold px-6">Отправить</button>
                    </div>
                </form>
            </div>
        @endif
    </div>

@endsection